permalink: /:title/
plugins:
  - jekyll-sitemap

title: iorgos.net
url: https://iorgos.net
baseurl: ""
description: "Personal website for Dragoș Iorgulescu"
author: Dragoș
twitter: DIorgulescu
stackoverflow: 1480784/sebbas
reddit: scentient_pencils
linkedin: 
youtube: UCiU3oTGKL4GDr5xgK_EMjnQ
username: diorgulescu
email: dragos@iorgos.net

timezone: Europe/Bucharest
google_analytics_tracking_id: U
